
trigger:
  - maste

pool:
  name: Criar RG e VNET
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'AzureRmPipeline.BrunoMattos'
    ScriptPath: 'Deploy-AzureResourceGroup.ps1'
    azurePowerShellVersion: LatestVersion

