trigger:
  - maste

pool:
  name: Criar RG e VNET
  demands: azureps

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureRmPipeline.BrunoMattos'
    ScriptType: 'InlineScript'
    Inline:
      $rg = Get-AzResourceGroup -Name "rs-gp-dev-001"
      $definition = Get-AzPolicyDefinition | Where-Object { $_.Properties.DisplayName -eq 'Inherit a tag from the resource group' }
      New-AzPolicyAssignment -Name “Inherit-tags” -DisplayName “Audit - Inherit tags” -Scope $rg.ResourceId -PolicyDefinition $definition
    azurePowerShellVersion: 'LatestVersion'
