
trigger:
  - maste

pool:
  name: Criar RG e VNET
  demands: azureps

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureRmPipeline.BrunoMattos'
    ScriptType: 'Deploy-AzureResourceGroup.ps1'
    azurePowerShellVersion: 'LatestVersion'